name: Build and Deploy
on: [push]
jobs:
  # 任务名称
  build-and-deploy:
    # 执行的环境，默认是在最新版本的Ubuntu系统
    runs-on: ubuntu-latest
    # 执行的步骤
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_KEY }}
          TARGET_REPO: cfmj/wetok-admin-doc
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: public
          # CNAME: https://www.xxx.com
# name: Build and Deploy
# on: # 监听 master 分支上的 push 事件
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest # 构建环境使用 ubuntu
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.1
#         with:
#           persist-credentials: false

#       - name: Install and Build # 下载依赖 打包项目
#         run: |
#           npm install
#           npm run build

#       - name: Deploy # 将打包内容发布到 github page
#         uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
#         with: # 自定义环境变量
#           ACCESS_TOKEN: ${{ secrets.GH_KEY }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
#           BRANCH: master
#           FOLDER: public
#           REPOSITORY_NAME: cfmj/wetok-admin-doc # 这是我的 github page 仓库
#           TARGET_FOLDER: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下

