name: Build and Deploy
on: [push]
jobs:
  # 任务名称
  build-and-deploy:
    # 执行的环境，默认是在最新版本的Ubuntu系统
    runs-on: ubuntu-latest
    # 执行的步骤
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_KEY }}
          TARGET_REPO: cfmj/wetok-admin-doc
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: public
          # CNAME: https://www.xxx.com
